/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/404': RouteRecordInfo<
      '/404',
      '/404',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/ablums/': RouteRecordInfo<
      '/ablums/',
      '/ablums',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/ablums/game': RouteRecordInfo<
      '/ablums/game',
      '/ablums/game',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/ablums/life': RouteRecordInfo<
      '/ablums/life',
      '/ablums/life',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/ablums/nijika': RouteRecordInfo<
      '/ablums/nijika',
      '/ablums/nijika',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/': RouteRecordInfo<
      '/about/',
      '/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/site': RouteRecordInfo<
      '/about/site',
      '/about/site',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/archives/': RouteRecordInfo<
      '/archives/',
      '/archives',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/bangumi/': RouteRecordInfo<
      '/bangumi/',
      '/bangumi',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/categories/': RouteRecordInfo<
      '/categories/',
      '/categories',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/collections/': RouteRecordInfo<
      '/collections/',
      '/collections',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/collections/lanqiao/': RouteRecordInfo<
      '/collections/lanqiao/',
      '/collections/lanqiao',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/collections/lanqiao/1': RouteRecordInfo<
      '/collections/lanqiao/1',
      '/collections/lanqiao/1',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/collections/lanqiao/10': RouteRecordInfo<
      '/collections/lanqiao/10',
      '/collections/lanqiao/10',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/collections/lanqiao/11': RouteRecordInfo<
      '/collections/lanqiao/11',
      '/collections/lanqiao/11',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/collections/lanqiao/12': RouteRecordInfo<
      '/collections/lanqiao/12',
      '/collections/lanqiao/12',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/collections/lanqiao/13': RouteRecordInfo<
      '/collections/lanqiao/13',
      '/collections/lanqiao/13',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/collections/lanqiao/2': RouteRecordInfo<
      '/collections/lanqiao/2',
      '/collections/lanqiao/2',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/collections/lanqiao/3': RouteRecordInfo<
      '/collections/lanqiao/3',
      '/collections/lanqiao/3',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/collections/lanqiao/4': RouteRecordInfo<
      '/collections/lanqiao/4',
      '/collections/lanqiao/4',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/collections/lanqiao/5': RouteRecordInfo<
      '/collections/lanqiao/5',
      '/collections/lanqiao/5',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/collections/lanqiao/6': RouteRecordInfo<
      '/collections/lanqiao/6',
      '/collections/lanqiao/6',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/collections/lanqiao/7': RouteRecordInfo<
      '/collections/lanqiao/7',
      '/collections/lanqiao/7',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/collections/lanqiao/8': RouteRecordInfo<
      '/collections/lanqiao/8',
      '/collections/lanqiao/8',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/collections/lanqiao/9': RouteRecordInfo<
      '/collections/lanqiao/9',
      '/collections/lanqiao/9',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/girls/': RouteRecordInfo<
      '/girls/',
      '/girls',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/links/': RouteRecordInfo<
      '/links/',
      '/links',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/page/[page]': RouteRecordInfo<
      '/page/[page]',
      '/page/:page',
      { page: ParamValue<true> },
      { page: ParamValue<false> },
      | never
    >,
    '/posts/': RouteRecordInfo<
      '/posts/',
      '/posts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/优先队列自定义排序': RouteRecordInfo<
      '/posts/优先队列自定义排序',
      '/posts/%E4%BC%98%E5%85%88%E9%98%9F%E5%88%97%E8%87%AA%E5%AE%9A%E4%B9%89%E6%8E%92%E5%BA%8F',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/使用 pyenv 管理多个 Python 版本': RouteRecordInfo<
      '/posts/使用 pyenv 管理多个 Python 版本',
      '/posts/%E4%BD%BF%E7%94%A8%20pyenv%20%E7%AE%A1%E7%90%86%E5%A4%9A%E4%B8%AA%20Python%20%E7%89%88%E6%9C%AC',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/动漫图片分类助手：一个基于 AI 的动漫角色识别与整理工具': RouteRecordInfo<
      '/posts/动漫图片分类助手：一个基于 AI 的动漫角色识别与整理工具',
      '/posts/%E5%8A%A8%E6%BC%AB%E5%9B%BE%E7%89%87%E5%88%86%E7%B1%BB%E5%8A%A9%E6%89%8B%EF%BC%9A%E4%B8%80%E4%B8%AA%E5%9F%BA%E4%BA%8E%20AI%20%E7%9A%84%E5%8A%A8%E6%BC%AB%E8%A7%92%E8%89%B2%E8%AF%86%E5%88%AB%E4%B8%8E%E6%95%B4%E7%90%86%E5%B7%A5%E5%85%B7',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/图论可视化工具：一个轻量级的在线图形编辑与分析平台': RouteRecordInfo<
      '/posts/图论可视化工具：一个轻量级的在线图形编辑与分析平台',
      '/posts/%E5%9B%BE%E8%AE%BA%E5%8F%AF%E8%A7%86%E5%8C%96%E5%B7%A5%E5%85%B7%EF%BC%9A%E4%B8%80%E4%B8%AA%E8%BD%BB%E9%87%8F%E7%BA%A7%E7%9A%84%E5%9C%A8%E7%BA%BF%E5%9B%BE%E5%BD%A2%E7%BC%96%E8%BE%91%E4%B8%8E%E5%88%86%E6%9E%90%E5%B9%B3%E5%8F%B0',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/头歌包过教程(对付给看输出的那种)': RouteRecordInfo<
      '/posts/头歌包过教程(对付给看输出的那种)',
      '/posts/%E5%A4%B4%E6%AD%8C%E5%8C%85%E8%BF%87%E6%95%99%E7%A8%8B(%E5%AF%B9%E4%BB%98%E7%BB%99%E7%9C%8B%E8%BE%93%E5%87%BA%E7%9A%84%E9%82%A3%E7%A7%8D)',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/崩溃了,AI': RouteRecordInfo<
      '/posts/崩溃了,AI',
      '/posts/%E5%B4%A9%E6%BA%83%E4%BA%86,AI',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/新年快乐': RouteRecordInfo<
      '/posts/新年快乐',
      '/posts/%E6%96%B0%E5%B9%B4%E5%BF%AB%E4%B9%90',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/更好的在.md文件粘贴图片-Paste image VScode插件推荐': RouteRecordInfo<
      '/posts/更好的在.md文件粘贴图片-Paste image VScode插件推荐',
      '/posts/%E6%9B%B4%E5%A5%BD%E7%9A%84%E5%9C%A8/md%E6%96%87%E4%BB%B6%E7%B2%98%E8%B4%B4%E5%9B%BE%E7%89%87-Paste%20image%20VScode%E6%8F%92%E4%BB%B6%E6%8E%A8%E8%8D%90',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/给你的GitHubpage用上Cloudflare(只有域名即可)': RouteRecordInfo<
      '/posts/给你的GitHubpage用上Cloudflare(只有域名即可)',
      '/posts/%E7%BB%99%E4%BD%A0%E7%9A%84GitHubpage%E7%94%A8%E4%B8%8ACloudflare(%E5%8F%AA%E6%9C%89%E5%9F%9F%E5%90%8D%E5%8D%B3%E5%8F%AF)',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/bocchi-the-rock-theme for VSCode': RouteRecordInfo<
      '/posts/bocchi-the-rock-theme for VSCode',
      '/posts/bocchi-the-rock-theme%20for%20VSCode',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/C++容器操作优化': RouteRecordInfo<
      '/posts/C++容器操作优化',
      '/posts/C++%E5%AE%B9%E5%99%A8%E6%93%8D%E4%BD%9C%E4%BC%98%E5%8C%96',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/hello': RouteRecordInfo<
      '/posts/hello',
      '/posts/hello',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/TypePost': RouteRecordInfo<
      '/posts/TypePost',
      '/posts/TypePost',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/projects/': RouteRecordInfo<
      '/projects/',
      '/projects',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tags/': RouteRecordInfo<
      '/tags/',
      '/tags',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'node_modules/.pnpm/valaxy-theme-yun@0.28.11_magicast@0.5.3_vue@3.5.38_typescript@5.9.3_/node_modules/valaxy-theme-yun/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
      pathParamNames:
        | never
    }
    'node_modules/.pnpm/valaxy@0.28.11_@babel+parser@7.29.7_@nuxt+kit@3.21.8_magicast@0.5.3__@types+markdown-it@14.1._rvideu56nahko2r6zzcuu27lku/node_modules/valaxy/client/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
      pathParamNames:
        | 'path'
    }
    'pages/404.md': {
      routes:
        | '/404'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/ablums/index.md': {
      routes:
        | '/ablums/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/ablums/game.md': {
      routes:
        | '/ablums/game'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/ablums/life.md': {
      routes:
        | '/ablums/life'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/ablums/nijika.md': {
      routes:
        | '/ablums/nijika'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/about/index.md': {
      routes:
        | '/about/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/about/site.md': {
      routes:
        | '/about/site'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/archives/index.md': {
      routes:
        | '/archives/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/bangumi/index.md': {
      routes:
        | '/bangumi/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/categories/index.md': {
      routes:
        | '/categories/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/collections/index.md': {
      routes:
        | '/collections/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/collections/lanqiao/index.md': {
      routes:
        | '/collections/lanqiao/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/collections/lanqiao/1.md': {
      routes:
        | '/collections/lanqiao/1'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/collections/lanqiao/10.md': {
      routes:
        | '/collections/lanqiao/10'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/collections/lanqiao/11.md': {
      routes:
        | '/collections/lanqiao/11'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/collections/lanqiao/12.md': {
      routes:
        | '/collections/lanqiao/12'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/collections/lanqiao/13.md': {
      routes:
        | '/collections/lanqiao/13'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/collections/lanqiao/2.md': {
      routes:
        | '/collections/lanqiao/2'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/collections/lanqiao/3.md': {
      routes:
        | '/collections/lanqiao/3'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/collections/lanqiao/4.md': {
      routes:
        | '/collections/lanqiao/4'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/collections/lanqiao/5.md': {
      routes:
        | '/collections/lanqiao/5'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/collections/lanqiao/6.md': {
      routes:
        | '/collections/lanqiao/6'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/collections/lanqiao/7.md': {
      routes:
        | '/collections/lanqiao/7'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/collections/lanqiao/8.md': {
      routes:
        | '/collections/lanqiao/8'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/collections/lanqiao/9.md': {
      routes:
        | '/collections/lanqiao/9'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/girls/index.md': {
      routes:
        | '/girls/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/links/index.md': {
      routes:
        | '/links/'
      views:
        | never
      pathParamNames:
        | never
    }
    'node_modules/.pnpm/valaxy-theme-yun@0.28.11_magicast@0.5.3_vue@3.5.38_typescript@5.9.3_/node_modules/valaxy-theme-yun/pages/page/[page].vue': {
      routes:
        | '/page/[page]'
      views:
        | never
      pathParamNames:
        | 'page'
    }
    'node_modules/.pnpm/valaxy-theme-yun@0.28.11_magicast@0.5.3_vue@3.5.38_typescript@5.9.3_/node_modules/valaxy-theme-yun/pages/posts/index.vue': {
      routes:
        | '/posts/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/优先队列自定义排序.md': {
      routes:
        | '/posts/优先队列自定义排序'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/使用 pyenv 管理多个 Python 版本.md': {
      routes:
        | '/posts/使用 pyenv 管理多个 Python 版本'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/动漫图片分类助手：一个基于 AI 的动漫角色识别与整理工具.md': {
      routes:
        | '/posts/动漫图片分类助手：一个基于 AI 的动漫角色识别与整理工具'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/图论可视化工具：一个轻量级的在线图形编辑与分析平台.md': {
      routes:
        | '/posts/图论可视化工具：一个轻量级的在线图形编辑与分析平台'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/头歌包过教程(对付给看输出的那种).md': {
      routes:
        | '/posts/头歌包过教程(对付给看输出的那种)'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/崩溃了,AI.md': {
      routes:
        | '/posts/崩溃了,AI'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/新年快乐.md': {
      routes:
        | '/posts/新年快乐'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/更好的在.md文件粘贴图片-Paste image VScode插件推荐.md': {
      routes:
        | '/posts/更好的在.md文件粘贴图片-Paste image VScode插件推荐'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/给你的GitHubpage用上Cloudflare(只有域名即可).md': {
      routes:
        | '/posts/给你的GitHubpage用上Cloudflare(只有域名即可)'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/bocchi-the-rock-theme for VSCode.md': {
      routes:
        | '/posts/bocchi-the-rock-theme for VSCode'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/C++容器操作优化.md': {
      routes:
        | '/posts/C++容器操作优化'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/hello.md': {
      routes:
        | '/posts/hello'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/TypePost.md': {
      routes:
        | '/posts/TypePost'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/projects/index.md': {
      routes:
        | '/projects/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/tags/index.md': {
      routes:
        | '/tags/'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
